### ISSUE TITLE
The sample json does not work properly when award is true

### ISSUE THREAD

**Issue by mzshieh** [spotboard/spotboard#10]
I try to use spotboard as a resolver (Award mode). I just use `grunt` to generate directory `dist`, then run `python3 -m http.server` in that directory to provide a web server on port 8000. I used the URL `http://localhost:8000/index.html?award=true` to open the spotboard in award mode, but all results have been revealed. I expected there should be pending runs colored in yellow, however, all submissions are either solved or rejected.

![2017-09-24-115732_1280x1056_scrot](https://user-images.githubusercontent.com/17217258/30779317-caa34778-a11f-11e7-9a66-9b7843b1d457.png)

**Comment by wookayin** [comment]
Sorry I have not made a proper documentation. You need to specify a query string `r=?` to specify how much runs would be revealed before award mode starts. It is defined to be the maximum number of run "id" that are to be revealed.

**Comment by mzshieh** [comment]
Thanks. It works. 2017 ACM-ICPC Hua-Lien Regionals probably will use spotboard for resolver. Thanks for your help.

**Comment by wookayin** [comment]
Great to hear that! Please feel free to ask me if you have any other question or need some technical support.
