### ISSUE TITLE
우선순위 플립이 안되는 경우가 있습니다.

### ISSUE THREAD

**Issue by cannalee90** [spotboard/spotboard#3]
우선순위 플립을 알파벳으로 설정하면 안되는 버그가 있습니다.

**Comment by wookayin** [comment]
정확한 이슈 설명과 혹은 구체적으로 버그를 재현하는 방법을 알려주시면 참고하겠습니다.

**Comment by cannalee90** [comment]
https://ide.c9.io/cannalee90/award_normal

급하게 셋팅할일이 있어서 여기서 시험해봤습니다.. 

여기서 우선 순위 플립플랍이 안되서 왜 안되는지

**Comment by wookayin** [comment]
Closed via #12.
